# **1. Load data**

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/superstore.csv')
df = pd.DataFrame(data)
print("rows,cols:", df.shape)

rows,cols: (9994, 21)

In [ ]:
new_column_names = {
    'Row ID': 'row_id',
    'Order ID': 'order_id',
    'Order Date': 'order_date',
    'Ship Date': 'ship_date',
    'Ship Mode': 'ship_mode',
    'Customer ID': 'customer_id',
    'Customer Name': 'customer_name',
    'Segment': 'segment',
    'Country': 'country',
    'City': 'city',
    'State': 'state',
    'Postal Code': 'postal_code',
    'Region': 'region',
    'Product ID': 'product_id',
    'Category': 'category',
    'Sub-Category': 'sub_category',
    'Product Name': 'product_name',
    'Sales': 'sales',
    'Quantity': 'quantity',
    'Discount': 'discount',
    'Profit': 'profit'
}

df.rename(columns=new_column_names, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9994 non-null   int64
 1   order_id       9994 non-null   object
 2   order_date     9994 non-null   object
 3   ship_date      9994 non-null   object
 4   ship_mode      9994 non-null   object
 5   customer_id    9994 non-null   object
 6   customer_name  9994 non-null   object
 7   segment        9994 non-null   object
 8   country        9994 non-null   object
 9   city           9994 non-null   object
 10  state          9994 non-null   object
 11  postal_code    9983 non-null   float64
 12  region         9994 non-null   object
 13  product_id     9994 non-null   object
 14  category       9994 non-null   object
 15  sub_category   9994 non-null   object
 16  product_name   9994 non-null   object
 17  sales          9994 non-null   float64
 18  quantity       9994 non-null   int64
 19  discount       9994 non-null   float64
 20  profit         9994 non-null   float64
dtypes: float64(4), int64(2), object(15)
memory usage: 1.6+ MB

# **2. Thực hành query**

In [ ]:
# Câu 1: Hiển thị 5 dòng dữ liệu đầu tiên để xem cấu trúc bảng.
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
# Câu 2: Hiển thị xem thử 5 đơn hàng ở khu vực miền Tây, và chỉ cần biết thông tin về Vùng, Tên sản phẩm và Doanh số của các đơn đó.
result = df.loc[df['region'] == 'West', ['region', 'product_name', 'sales']].head()
print(result)

  region                                       product_name    sales
2   West  Self-Adhesive Address Labels for Typewriters b...   14.620
5   West  Eldon Expressions Wood and Plastic Desk Access...   48.860
6   West                                         Newell 322    7.280
7   West                     Mitel 5320 IP Phone VoIP phone  907.152
8   West  DXL Angle-View Binders with Locking Rings by S...   18.504

In [ ]:
# Câu 3: Tính Tổng doanh thu, Tổng số đơn hàng (mã order_id duy nhất) và Tổng số lượng khách hàng duy nhất của toàn bộ cửa hàng.
pd.DataFrame({
    'total_sales': [df['sales'].sum()],
    'total_orders': [df['order_id'].nunique()],
    'unique_customers': [df['customer_id'].nunique()]
})

    total_sales  total_orders  unique_customers
0  2.297201e+06          5009               793

In [ ]:
# Câu 4: Phân tích Vùng (region) nào mang lại doanh số lớn nhất, sắp xếp từ cao xuống thấp.
(df.groupby('region')['sales']
   .sum()
   .reset_index(name='total_sales')
   .sort_values(by='total_sales', ascending=False)
)

    region  total_sales
3     West  725457.8245
1     East  678781.2400
0  Central  501239.8908
2    South  391721.9050

In [ ]:
# Câu 5: Xác định Danh mục (category) nào tạo ra nhiều lợi nhuận nhất.
(df.groupby('category')['profit']
   .sum()
   .reset_index(name='total_profit')
   .sort_values(by='total_profit', ascending=False)
)

          category  total_profit
2       Technology   145454.9481
1  Office Supplies   122490.8008
0        Furniture    18451.2728

In [ ]:
# Câu 6: Tìm 5 sản phẩm (product_name) có tổng doanh số cao nhất.
(df.groupby('product_name')['sales']
   .sum()
   .reset_index(name='total_sales')
   .sort_values(by='total_sales', ascending=False)
   .head(5)
)

                                          product_name  total_sales
404              Canon imageCLASS 2200 Advanced Copier    61599.824
650  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
444  Cisco TelePresence System EX90 Videoconferenci...    22638.480
786       HON 5400 Series Task Chairs for Big and Tall    21870.576
686         GBC DocuBind TL300 Electric Binding System    19823.479

In [ ]:
# Câu 7: Gom nhóm kết hợp theo category và sub_category để xem chi tiết mảng nào mang lại doanh thu cao nhất.
(df.groupby(['category', 'sub_category'])['sales']
   .sum()
   .reset_index(name='revenue')
   .sort_values(by='revenue', ascending=False)
)

           category sub_category      revenue
16       Technology       Phones  330007.0540
1         Furniture       Chairs  328449.1030
11  Office Supplies      Storage  223843.6080
3         Furniture       Tables  206965.5320
6   Office Supplies      Binders  203412.7330
15       Technology     Machines  189238.6310
13       Technology  Accessories  167380.3180
14       Technology      Copiers  149528.0300
0         Furniture    Bookcases  114879.9963
4   Office Supplies   Appliances  107532.1610
2         Furniture  Furnishings   91705.1640
10  Office Supplies        Paper   78479.2060
12  Office Supplies     Supplies   46673.5380
5   Office Supplies          Art   27118.7920
7   Office Supplies    Envelopes   16476.4020
9   Office Supplies       Labels   12486.3120
8   Office Supplies    Fasteners    3024.2800

In [ ]:
# Câu 8: Trích xuất năm từ cột ngày đặt hàng (order_date) và tính tổng doanh thu theo từng năm để xem đà tăng trưởng.
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

(df.groupby(df['order_date'].dt.year)['sales']
   .sum()
   .reset_index(name='revenue')
)

   order_date      revenue
0        2015  484247.4981
1        2016  470532.5090
2        2017  609205.5980
3        2018  733215.2552

In [ ]:
# Câu 9: Tính tổng doanh thu chi tiết theo từng tháng, nhưng chỉ giới hạn dữ liệu trong năm 2018.
# Tạo cột order_month ở định dạng YYYY-MM
# 1. Đảm bảo cột định dạng datetime
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

# 2. Lọc, Tạo cột tháng và Gom nhóm
result = (
    df[df['order_date'].dt.year == 2018]                    # Lọc riêng năm 2018
    .assign(order_month=df['order_date'].dt.to_period('M')) # Tạo cột tháng-năm
    .groupby('order_month')['sales']                        # Gom nhóm theo tháng
    .sum()                                                  # Tính tổng doanh thu
    .reset_index(name='total_sales')                        # Đưa về dạng bảng
)

result

   order_month  total_sales
0      2018-01   43971.3740
1      2018-02   20301.1334
2      2018-03   58872.3528
3      2018-04   36521.5361
4      2018-05   44261.1102
5      2018-06   52981.7257
6      2018-07   45264.4160
7      2018-08   63120.8880
8      2018-09   87866.6520
9      2018-10   77776.9232
10     2018-11  118447.8250
11     2018-12   83829.3188

In [ ]:
# Câu 10: Phòng Marketing muốn gửi quà tri ân cho các khách hàng VIP.
# Cần tìm danh sách các khách hàng (customer_name) có tổng doanh số (sales) mua hàng từ trước đến nay lớn hơn 14400, và sắp xếp danh sách này từ cao xuống thấp.
result = (
    df.groupby('customer_name')['sales']
    .sum()
    .reset_index(name='revenue')
    .loc[lambda x: x['revenue'] > 14400]
    .sort_values(by='revenue', ascending=False)
)

result

     customer_name    revenue
686    Sean Miller  25043.050
730   Tamara Chand  19052.218
622   Raymond Buch  15117.339
757   Tom Ashbrook  14595.620
6    Adrian Barton  14473.571